### PR TITLE
Add ELIXIR TtT events

### PR DESCRIPTION
**Pull request by khaled196**
This pull request to Add ELIXIR TtT events to train the trainer page

### CODE REVIEW

**Review by abotzki — COMMENTED** [review]
Thanks for providing the snippet for the train-the-trainer courses

**Review by abotzki — COMMENTED** [review]
Thanks

**Comment by poterlowicz-lab** [comment]
Thank you @abotzki  for the quick review

**Comment by khaled196** [comment]
Thank you @abotzki, I have changed the Widget type to a list for better readability and the website theme.

**Review by bpiereck — APPROVED** [review]

**Pull request merged**
